version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./data:/export
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /export
