# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  s3-unpacker

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # This is an SQS queue with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
  IncomingFilesQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900

  ExtractFile:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that extracts a zip file
      Runtime: nodejs14.x
      Handler: src/handlers/extractFile.handler
      MemorySize: 4192
      Timeout: 900
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Environment:
        Variables:
          OUTPUT_BUCKET: unpacked-zip-files
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt IncomingFilesQueue.Arn
  
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  # SQSPayloadLogger:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
  #     Runtime: nodejs14.x
  #     Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
  #     # This property associates this Lambda function with the SQS queue defined above, so that whenever the queue
  #     # receives a message, the Lambda function is invoked
  #     Events:
  #       SQSQueueEvent:
  #         Type: SQS
  #         Properties:
  #           Queue: Fn::GetAtt IncomingFilesQueue.Arn
  #     MemorySize: 128
  #     Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
  #     Policies:
  #       # Give Lambda basic execution Permission to the helloFromLambda
  #       - AWSLambdaBasicExecutionRole